### ISSUE TITLE
Inconsistent measurement

### ISSUE THREAD

**Issue by duanemoody** [synalysis/Grammars#8]
https://github.com/synalysis/Grammars/blob/2892dc9ebc46f317bc57a7c589542b6d70334477/stl.grammar#L17
The X vertex is measured as 32 bits, but the Y and Z vertices are measured as 4 bytes without explanation for the difference. According to the STL specification all three vertices are unsigned 32-bit floating point values so I don't understand why they aren't all described using the same unit in the grammar here. Documentation for Synalyze It! doesn't indicate the first instance of a pattern needs to be defined differently, either.

**Comment by synalysis** [comment]
I'm not the author of the grammar (the author's email is mentioned in the <grammar> element) however I assume there's no special reason for the difference. As bytes usually consist of 8 bits both representations conform to the specification.

Is there any reason other than curiosity for bringing this up?

**Comment by duanemoody** [comment]
Curiosity alone. Thank you for humoring me.
